package com.pcs.entities;
// Generated Nov 3, 2018 4:03:46 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StudentRegistration generated by hbm2java
 */
@Entity
@Table(name = "student_registration", catalog = "ptutors_dbs", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class StudentRegistration implements java.io.Serializable {

	private Integer studentId;
	private String email;
	private String password;
	private String sname;
	private String gender;
	private String dob;
	private String address1;
	private String address2;
	private String address3;
	private String country;
	private String state;
	private Long pincode;
	private Long contactNo;

	public StudentRegistration() {
	}

	public StudentRegistration(String email, String password, String sname) {
		this.email = email;
		this.password = password;
		this.sname = sname;
	}

	public StudentRegistration(String email, String password, String sname, String gender, String dob, String address1,
			String address2, String address3, String country, String state, Long pincode, Long contactNo) {
		this.email = email;
		this.password = password;
		this.sname = sname;
		this.gender = gender;
		this.dob = dob;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.country = country;
		this.state = state;
		this.pincode = pincode;
		this.contactNo = contactNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_id", unique = true, nullable = false)
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "sname", nullable = false, length = 200)
	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "dob", length = 100)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "address1", length = 200)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 200)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "address3", length = 200)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "pincode")
	public Long getPincode() {
		return this.pincode;
	}

	public void setPincode(Long pincode) {
		this.pincode = pincode;
	}

	@Column(name = "contact_no")
	public Long getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(Long contactNo) {
		this.contactNo = contactNo;
	}

}
